"""
app/state.py — LangGraph Shared State Schema (Architecture v2)

PURPOSE:
    Defines the single shared state object that flows through the entire LangGraph
    pipeline. Every agent reads from this and writes back to it.

ARCHITECTURE v2 CHANGES (from design document + diagrams):
    - Added: generated_python (str)       → LLM-written Python code from PythonAgent
    - Added: execution_results (dict)     → DataFrames, stats, text from ExecutorAgent
    - Added: charts (List[dict])          → Multiple Plotly charts (was a single dict)
    - Added: intent (str)                 → Top-level intent field (mirroring design doc schema)
    - Changed: insights (str → List[str]) → Multiple insight strings as per design doc
    - Removed: analysis_results           → Replaced by execution_results
    - Removed: plotly_chart_json          → Replaced by charts list

LangGraph STATE RULES:
    - Each agent receives the FULL state and returns ONLY the keys it updates.
    - LangGraph merges the returned dict back into the state automatically.
    - Fields annotated with `Annotated[List, operator.add]` are ACCUMULATED
      (each agent appends to them) rather than overwritten.
"""

from typing import Dict, List, Any, TypedDict, Annotated
import operator


class QueryState(TypedDict):
    """
    LangGraph Shared State — the single source of truth flowing through all 8 agents.

    Data flows in this order through the state:
      user_query
        → [Planner]      fills: intent, plan
        → [Schema]       fills: schema_context
        → [SQL]          fills: generated_sql
        → [Validator]    fills: sql_validation, may update generated_sql
        → [Redshift]     fills: query_results
        → [PythonAgent]  fills: generated_python
        → [Executor]     fills: execution_results, charts
        → [Insights]     fills: insights
    """

    # -------------------------------------------------------------------------
    # INPUT
    # -------------------------------------------------------------------------

    # The raw natural language question from the user (e.g., "Top 5 products by revenue?")
    user_query: str

    # -------------------------------------------------------------------------
    # PLANNER AGENT OUTPUT
    # -------------------------------------------------------------------------

    # Top-level intent string (e.g., "trend_analysis", "aggregation", "ranking")
    # Extracted separately from plan so downstream agents can reference it quickly
    intent: str

    # Structured execution plan from the PlannerAgent:
    # {
    #   "intent": "...",
    #   "analytical_objective": "...",
    #   "key_filters": [...],
    #   "time_period": "...",
    #   "grouping_dimensions": [...],
    #   "expected_output_type": "...",
    #   "complexity": "...",
    #   "plan_summary": "..."
    # }
    plan: Dict[str, Any]

    # -------------------------------------------------------------------------
    # SCHEMA AGENT OUTPUT
    # -------------------------------------------------------------------------

    # Relevant schema context from the SchemaAgent:
    # {
    #   "relevant_tables": [{"table_name": "...", "reason": "...", "relevant_columns": [...]}],
    #   "join_hints": "...",
    #   "schema_notes": "...",
    #   "all_available_tables": [...]
    # }
    schema_context: Dict[str, Any]

    # -------------------------------------------------------------------------
    # SQL AGENT OUTPUT
    # -------------------------------------------------------------------------

    # The executable Redshift SQL query string generated by SQLAgent
    generated_sql: str

    # -------------------------------------------------------------------------
    # VALIDATION AGENT OUTPUT
    # -------------------------------------------------------------------------

    # SQL validation result from ValidationAgent:
    # {
    #   "is_valid": bool,
    #   "issues": [...],
    #   "corrected_sql": "...",
    #   "confidence": "high|medium|low",
    #   "review_notes": "..."
    # }
    sql_validation: Dict[str, Any]

    # -------------------------------------------------------------------------
    # REDSHIFT EXECUTION NODE OUTPUT
    # -------------------------------------------------------------------------

    # Raw rows returned from Amazon Redshift, as list of dicts.
    # Each dict = one row, column names are keys.
    # e.g., [{"product": "Widget A", "total_sales": 150000}, ...]
    query_results: List[Dict[str, Any]]

    # -------------------------------------------------------------------------
    # PYTHON AGENT OUTPUT (NEW in Architecture v2)
    # -------------------------------------------------------------------------

    # LLM-generated Python code string from PythonAgent.
    # This is Pandas/NumPy/Plotly code that operates on `query_results`.
    # The code is WRITTEN by Claude, then EXECUTED by ExecutorAgent.
    #
    # Example of what this code looks like:
    #   import pandas as pd
    #   import plotly.express as px
    #   df = pd.DataFrame(query_results)
    #   top_10 = df.nlargest(10, 'total_sales')
    #   fig = px.bar(top_10, x='product', y='total_sales', title='Top 10 Products')
    #   charts.append(fig.to_dict())
    generated_python: str

    # -------------------------------------------------------------------------
    # EXECUTOR AGENT OUTPUT (NEW in Architecture v2)
    # -------------------------------------------------------------------------

    # Structured results dict from ExecutorAgent after executing generated_python.
    # Contains whatever the code produced: DataFrames, statistics, text outputs.
    # {
    #   "dataframes": {"df_name": [...records...]},
    #   "statistics": {"metric": value, ...},
    #   "text_outputs": ["some computed string", ...],
    #   "error": null or "error message if execution failed"
    # }
    execution_results: Dict[str, Any]

    # List of Plotly chart JSON dicts produced during execution.
    # Each chart can be rendered directly by React-Plotly on the frontend.
    # Architecture v2 explicitly allows MULTIPLE charts per query.
    # e.g., [bar_chart_dict, line_chart_dict]
    charts: List[Dict[str, Any]]

    # -------------------------------------------------------------------------
    # INSIGHTS AGENT OUTPUT (Updated in Architecture v2)
    # -------------------------------------------------------------------------

    # List of insight strings from InsightsAgent (was a single string in v1).
    # Architecture v2 design doc specifies insights as a list, allowing:
    # - One headline insight
    # - Multiple supporting findings
    # - Recommendations
    insights: List[str]

    # -------------------------------------------------------------------------
    # SYSTEM / ROUTING FIELDS
    # -------------------------------------------------------------------------

    # Error message if any agent or node fails.
    # Used by conditional edges to route away from failed paths.
    # Empty string "" means no error.
    error: str

    # Execution trace log — each agent APPENDS to this list using operator.add.
    # The `Annotated[List, operator.add]` annotation tells LangGraph to MERGE
    # (not overwrite) this field when agents return partial state updates.
    # Frontend uses this to show a live step-by-step progress indicator.
    # e.g., ["✅ Planner: intent=aggregation", "✅ Schema: tables=[sales]", ...]
    step_log: Annotated[List[str], operator.add]
