"""
agents/executor.py — Python Code Executor Agent (Architecture v2)

ROLE IN THE PIPELINE:
    Step 7. Runs after PythonAgent. The second new agent in Architecture v2.

WHAT IT DOES:
    Takes the Python code string generated by PythonAgent and executes it
    inside a restricted, sandboxed environment using Python's exec() function.
    
    Captures three types of outputs:
    1. `charts`       — List of Plotly figure dicts for the frontend
    2. `statistics`   — Dict of computed metrics (numbers, percentages)
    3. `text_outputs` — List of text findings from the analysis

WHY exec() IS SAFE HERE (the key insight from excecuter_agent.py):
    We don't use a fully open exec(). Instead, we:
    1. Create a RESTRICTED __builtins__ dict that ONLY allows safe Python built-ins
    2. Block all file/system access: no open(), no os, no subprocess
    3. Inject ONLY trusted modules: pandas, numpy, plotly — already installed, vetted
    4. Set a hard timeout to prevent infinite loops
    5. Run code that came from OUR OWN LLM (not user input)

    This approach is directly adapted from the reference excecuter_agent.py which uses:
    `_EXEC_RESTRICTED_BUILTINS` to whitelist safe builtins, then injects
    data reading helpers into the execution namespace.

DIFFERENCE FROM REFERENCE CODE:
    The reference executor was designed to run user-submitted data science code.
    Our executor only runs LLM-generated code that we control.
    This means we can be slightly more permissive (e.g., allow math operations)
    while still blocking system-level access.

TIMEOUT:
    Uses Python's signal module for Mac/Linux. On Windows, we use threading.
    WHY both? Because we need to work on your Mac NOW and Windows LATER.
"""

import logging
import json
import math
import re
import sys
import threading
from typing import Dict, Any, List

import pandas as pd
import numpy as np
import plotly
import plotly.express as px
import plotly.graph_objects as go

from ..state import QueryState

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SECURITY: Restricted __builtins__
# ---------------------------------------------------------------------------
# This whitelist is the core security layer, adapted directly from
# excecuter_agent.py's _EXEC_RESTRICTED_BUILTINS pattern.
#
# WHY whitelist instead of blacklist?
#   A blacklist (blocking known dangerous functions) is easy to bypass.
#   A whitelist (ONLY allowing known safe functions) is far more secure.
#   Even if we missed a dangerous function, it won't be available.
# ---------------------------------------------------------------------------
_SAFE_BUILTINS = {
    # Core Python builtins needed for data analysis
    "abs": abs, "all": all, "any": any, "bool": bool, "dict": dict,
    "dir": dir, "enumerate": enumerate, "filter": filter, "float": float,
    "format": format, "frozenset": frozenset, "getattr": getattr,
    "hasattr": hasattr, "hash": hash, "int": int, "isinstance": isinstance,
    "issubclass": issubclass, "iter": iter, "len": len, "list": list,
    "map": map, "max": max, "min": min, "next": next, "object": object,
    "print": print, "range": range, "repr": repr, "reversed": reversed,
    "round": round, "set": set, "slice": slice, "sorted": sorted, "str": str,
    "sum": sum, "tuple": tuple, "type": type, "vars": vars, "zip": zip,
    # Safe built-in exceptions (needed for try/except in generated code)
    "Exception": Exception, "ValueError": ValueError, "TypeError": TypeError,
    "KeyError": KeyError, "IndexError": IndexError, "ZeroDivisionError": ZeroDivisionError,
    # BLOCKED: open, exec, eval, __import__, compile, globals, locals
    # (not included in this dict = not available in exec() scope)
}

# Execution timeout in seconds — prevents infinite loops in generated code
_EXEC_TIMEOUT_SECONDS = 30


class ExecutionTimeoutError(Exception):
    """Raised when code execution exceeds the timeout limit."""
    pass


class ExecutorAgent:
    """
    Safely executes LLM-generated Python code in a restricted sandbox.

    This is the second new agent in Architecture v2. It pairs with PythonAgent:
    - PythonAgent writes the code
    - ExecutorAgent runs the code and captures outputs

    WHY separate agents?
        Code GENERATION and code EXECUTION are fundamentally different concerns.
        Separating them means we can:
        - Inspect the generated code before running it (e.g., for debugging)
        - Retry execution with different code if it fails
        - Log the generated code for auditing
    """

    def __init__(self):
        logger.info("ExecutorAgent initialized")

    def _build_execution_namespace(self, query_results: List[Dict]) -> Dict[str, Any]:
        """
        Build the execution namespace: all variables and modules available to the
        generated code when it runs inside exec().

        WHY a namespace dict?
            exec(code, globals, locals) runs code with the given global and local
            variable scopes. By providing our own namespace, we control exactly
            what the code can see and use.

        What's injected:
            - Pre-loaded trusted libraries (pd, np, px, go, etc.)
            - query_results: the actual data
            - Output collection variables (charts, statistics, text_outputs)
            - Restricted __builtins__

        Returns:
            dict: The namespace dict to pass to exec()
        """
        return {
            "__builtins__": _SAFE_BUILTINS,     # SECURITY: restricted built-ins only
            # Data science libraries (pre-imported, vetted, safe)
            "pd": pd,
            "np": np,
            "px": px,
            "go": go,
            "json": json,
            "math": math,
            "re": re,
            # Input data — the raw Redshift rows
            "query_results": query_results,
            # Output capture variables — code writes INTO these
            # The executor reads them back after execution
            "charts": [],           # List of Plotly chart dicts
            "statistics": {},       # Dict of computed metrics
            "text_outputs": [],     # List of text findings/summaries
        }

    def _execute_with_timeout(self, code: str, namespace: Dict) -> bool:
        """
        Execute code with a hard timeout using threading.

        WHY threading instead of signal.alarm?
            signal.alarm only works on Unix/Mac (SIGALRM). Since we need this to
            work on Windows too (your corporate laptop), we use threading.Timer
            which is cross-platform.

        Args:
            code:      The Python code string to execute
            namespace: The execution namespace dict

        Returns:
            bool: True if execution completed successfully, False if timed out
        """
        execution_error = [None]   # mutable container for error from thread
        completed = [False]        # flag to know if done

        def run():
            try:
                exec(code, namespace)
                completed[0] = True
            except Exception as e:
                execution_error[0] = e
                completed[0] = True  # completed with error

        thread = threading.Thread(target=run, daemon=True)
        thread.start()
        thread.join(timeout=_EXEC_TIMEOUT_SECONDS)

        if not completed[0]:
            raise ExecutionTimeoutError(
                f"Code execution exceeded {_EXEC_TIMEOUT_SECONDS} second timeout"
            )

        if execution_error[0] is not None:
            raise execution_error[0]

        return True

    def _serialize_charts(self, charts: list) -> List[Dict]:
        """
        Serialize Plotly chart dicts using PlotlyJSONEncoder to handle
        numpy arrays, NaN values, Infinity, etc.

        WHY PlotlyJSONEncoder?
            Plotly figures may contain numpy arrays and special float values (NaN, Inf)
            that standard JSON can't handle. PlotlyJSONEncoder handles these correctly.
            This is the same pattern as excecuter_agent.py's json.dumps call.
        """
        serialized = []
        for chart in charts:
            try:
                if hasattr(chart, "to_dict"):
                    # It's a Plotly Figure object — convert to dict first
                    chart = chart.to_dict()
                # Round-trip through JSON to normalize numpy types
                chart_json_str = json.dumps(chart, cls=plotly.utils.PlotlyJSONEncoder)
                serialized.append(json.loads(chart_json_str))
            except Exception as e:
                logger.warning(f"Could not serialize chart: {e}")
        return serialized

    def _serialize_statistics(self, statistics: dict) -> Dict[str, Any]:
        """
        Convert statistics dict values to JSON-safe Python types.
        numpy scalars (np.float64, np.int64) are not JSON serializable by default.
        """
        safe_stats = {}
        for key, value in statistics.items():
            try:
                if isinstance(value, (np.integer,)):
                    safe_stats[key] = int(value)
                elif isinstance(value, (np.floating,)):
                    safe_stats[key] = float(value)
                elif isinstance(value, np.ndarray):
                    safe_stats[key] = value.tolist()
                elif isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
                    safe_stats[key] = None  # Replace NaN/Inf with None
                else:
                    safe_stats[key] = value
            except Exception:
                safe_stats[key] = str(value)
        return safe_stats

    def process(self, state: QueryState) -> Dict[str, Any]:
        """
        LangGraph node function.

        Reads:
            state["generated_python"] — Python code string from PythonAgent
            state["query_results"]    — Raw data to inject into the sandbox

        Writes:
            state["execution_results"] — Dict with dataframes, statistics, text_outputs
            state["charts"]            — List of Plotly chart JSON dicts
        """
        code = state.get("generated_python", "")
        query_results = state.get("query_results", [])

        if not code or not code.strip():
            logger.warning("ExecutorAgent: No code to execute")
            return {
                "execution_results": {"error": "No Python code was generated"},
                "charts": [],
                "step_log": ["⚠️ Executor: No code to execute"],
            }

        logger.info(f"ExecutorAgent executing {len(code)} chars of code")
        logger.debug(f"Code preview:\n{code[:500]}")

        # Build the sandboxed execution namespace
        namespace = self._build_execution_namespace(query_results)

        try:
            # Execute the code with timeout protection
            self._execute_with_timeout(code, namespace)

            # --- Capture outputs from the namespace ---
            raw_charts = namespace.get("charts", [])
            raw_statistics = namespace.get("statistics", {})
            raw_text_outputs = namespace.get("text_outputs", [])

            # Serialize charts (handles numpy types, NaN, etc.)
            serialized_charts = self._serialize_charts(raw_charts)
            # Serialize statistics
            serialized_stats = self._serialize_statistics(raw_statistics)

            execution_results = {
                "statistics": serialized_stats,
                "text_outputs": [str(t) for t in raw_text_outputs],
                "total_charts": len(serialized_charts),
                "error": None,
            }

            logger.info(
                f"ExecutorAgent complete | charts={len(serialized_charts)} | "
                f"stats_keys={list(serialized_stats.keys())} | "
                f"text_outputs={len(raw_text_outputs)}"
            )

            return {
                "execution_results": execution_results,
                "charts": serialized_charts,
                "step_log": [
                    f"✅ Executor: Ran successfully | "
                    f"charts={len(serialized_charts)} | "
                    f"stats={len(serialized_stats)} keys | "
                    f"findings={len(raw_text_outputs)}"
                ],
            }

        except ExecutionTimeoutError as e:
            error_msg = f"Code execution timed out after {_EXEC_TIMEOUT_SECONDS}s"
            logger.error(error_msg)
            return {
                "execution_results": {"error": error_msg, "statistics": {}, "text_outputs": []},
                "charts": [],
                "error": error_msg,
                "step_log": [f"❌ Executor: TIMEOUT — {error_msg}"],
            }

        except Exception as e:
            error_msg = f"Code execution failed: {type(e).__name__}: {e}"
            logger.error(error_msg, exc_info=True)
            # Return partial results if any outputs were captured before the error
            partial_charts = self._serialize_charts(namespace.get("charts", []))
            partial_stats = self._serialize_statistics(namespace.get("statistics", {}))
            return {
                "execution_results": {
                    "error": error_msg,
                    "statistics": partial_stats,
                    "text_outputs": [str(t) for t in namespace.get("text_outputs", [])],
                },
                "charts": partial_charts,
                "error": error_msg,
                "step_log": [f"❌ Executor: Runtime error — {error_msg}"],
            }
